"""Generate static project pages and social preview cards. Requires Pillow."""
from pathlib import Path
from html import escape
from PIL import Image, ImageDraw, ImageFont
import json

ROOT = Path(__file__).parent
BASE = 'https://edrystarz.github.io'
PROJECTS = [
 dict(slug='stars-about-war', name='Stars About War', category='Extensions', status='Published', color='#d5e88c', tag='Context, right on YouTube.', description='See source-linked classifications beside YouTube channels and videos, without leaving the page.', detail='An unofficial extension displaying records from Stars About War. Labels link to the source so you can review its reasoning. Classifications belong to the source; this extension is not an independent fact-checker.', features=['Labels across YouTube feeds, search results and channel pages','Local channel matching and scheduled feed updates','Cached fallback data and Ukrainian / Russian localization'], stack='JavaScript · Manifest V3 · Chrome APIs', action='Install for Chrome', url='https://chromewebstore.google.com/detail/hehkapopfhfcoegmccjcdppmdmioigid', secondary='https://github.com/EdryStarz/EdryStarz/blob/main/projects/stars-about-war.md', secondary_label='Technical overview', note='Published in Chrome Web Store. Store version and availability can change.', motif='SOURCE → CHANNEL → CONTEXT'),
 dict(slug='alabuga-detector', name='Alabuga Detector', category='Extensions', status='Published', color='#f7aa89', tag='A label. A source. Your judgement.', description='Recognize YouTube channels listed in the Alabuga advertising database, with links to source material.', detail='A browser extension showing channel-level labels based on gubanovfiles.com. A label refers to the channel record, not necessarily the video you are watching. Review the original evidence before drawing conclusions.', features=['Local matching by channel ID, handle or unique name','Background database updates with a cached fallback','Available for Chrome and Firefox'], stack='JavaScript · WebExtensions · HTML / CSS', action='Install for Chrome', url='https://chromewebstore.google.com/detail/ngfbnchnfaijhmckphhfkhnackjbidog', secondary='https://addons.mozilla.org/en-US/firefox/addon/alabuga-channel-detector/', secondary_label='Install for Firefox', note='Published browser extension. Source records are maintained by gubanovfiles.com.', motif='CHANNEL → RECORD → SOURCE'),
 dict(slug='english-memory', name='English Memory', category='Learning', status='Prototype', color='#b8c6f3', tag='Hear it. Save it. Remember it.', description='Turn English from your microphone or PC audio into vocabulary cards with local AI and spaced repetition.', detail='A native Windows application using local Whisper transcription and language-model analysis. Your vocabulary lives in SQLite on your device. Model-generated translations and level labels need human review.', features=['Microphone / PC audio capture with explicit start and pause','Local vocabulary, subtitle imports and review scheduling','Windows x64 build verified; 74 default behavior checks passed'], stack='C# · .NET 10 · WinUI 3 · Whisper · SQLite', action='Get source & setup', url='https://github.com/EdryStarz/english-memory', secondary='https://github.com/EdryStarz/english-memory#build-and-run', secondary_label='Build instructions', note='Windows 11 x64. Requires building from source and downloading models. No installer is hosted here.', motif='LISTEN → CAPTURE → RECALL'),
 dict(slug='english-b2-tracker', name='English B2 Tracker', category='Learning', status='Prototype', color='#b8dcc8', tag='A plan you can actually follow.', description='A 12-week English study roadmap with daily tasks, vocabulary, an error log and progress stored in your browser.', detail='A local-first study planner built with Next.js and IndexedDB. It organizes practice and records progress; it does not certify B2 proficiency. Export JSON backups before clearing browser data.', features=['Daily tasks, weekly reflections and a study calendar','Vocabulary practice, focus timer and error log','Production build, lint and TypeScript checks passed'], stack='TypeScript · React · Next.js · IndexedDB', action='Get source & setup', url='https://github.com/EdryStarz/english-b2-tracker', secondary='https://github.com/EdryStarz/english-b2-tracker#run-locally', secondary_label='Run locally', note='This page introduces the project. It is not a hosted tracker demo. Initial sample entries are examples.', motif='PLAN → PRACTICE → PROGRESS'),
 dict(slug='textflow', name='TextFlow', category='Desktop', status='Prototype', color='#e4d4ae', tag='Type less. Keep your flow.', description='Reusable text snippets, global hotkeys and a quick-search palette for Windows.', detail='A portable Windows utility for Unicode text snippets, shortcuts and QuickTextPaste imports. Paste requests are serialized; the inserted text remains on the clipboard.', features=['Global hotkeys and a searchable snippet palette','Portable JSON storage and Win32 input integration','Nine behavior checks passed on Windows'], stack='C# · .NET 8 · WPF · Win32', action='Get source & setup', url='https://github.com/EdryStarz/TextFlow', secondary='https://github.com/EdryStarz/TextFlow#run-from-source', secondary_label='Run from source', note='Windows 10/11. Build from source with the .NET 8 SDK.', motif='SAVE → SEARCH → PASTE'),
 dict(slug='shorts-studio', name='Shorts Studio', category='Media', status='In Development', color='#d6bbef', tag='Long video. Short workflow.', description='A local video pipeline for transcription, clip ranking, vertical reframing and subtitles.', detail='A Python backend and React interface for local media processing. Completed pipeline stages can be reused. The frontend build was checked; a full Docker/media processing run was not verified in this portfolio review.', features=['Local faster-whisper transcription and scene analysis','Vertical reframing, subtitles and FFmpeg export','Stage persistence and optional publishing connectors'], stack='Python · FastAPI · React · FFmpeg', action='Explore the repository', url='https://github.com/EdryStarz/shorts-studio', secondary='https://github.com/EdryStarz/shorts-studio#run-with-docker', secondary_label='Docker setup', note='In development. External publishing requires configuration and is disabled by default.', motif='TRANSCRIBE → FRAME → EXPORT'),
 dict(slug='windows-counter', name='Windows Counter', category='Desktop', status='Prototype', color='#d2d5ce', tag='One number. Always there.', description='A compact Windows desktop counter with keyboard controls and persistent storage.', detail='A focused Tkinter utility with increment, decrement, manual values and always-on-top mode. Atomic writes preserve the current value between sessions.', features=['Buttons, arrow keys and manual integer input','Always-on-top mode and reset confirmation','Persistence and malformed-data fallback verified'], stack='Python · Tkinter', action='Get source & setup', url='https://github.com/EdryStarz/windows-counter', secondary='https://github.com/EdryStarz/windows-counter#run-from-source', secondary_label='Run from source', note='Python 3.10 or newer with Tkinter. Source project; no installer is hosted here.', motif='COUNT → SAVE → CONTINUE')
]

def header(title, description, path='', image='assets/overview.png'):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(description,quote=True)}"><link rel="canonical" href="{BASE}/{path}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:url" content="{BASE}/{path}"><meta property="og:image" content="{BASE}/{image}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/script.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="nav"><a class="brand" href="/">edry<span>starz</span><i aria-hidden="true">✳</i></a><nav aria-label="Main"><a href="/#projects">Projects</a><a href="https://github.com/EdryStarz">GitHub ↗</a></nav></header>'''

def footer():
 return '''<footer><a class="brand" href="/">edrystarz</a><p>Useful software. Clear sources. Honest project status.</p><a href="https://github.com/EdryStarz">Explore the code ↗</a></footer><div id="feedback" role="status" aria-live="polite"></div></body></html>'''

def share(url):
 return f'''<div class="share"><button type="button" data-share="{url}">Share this project ↗</button><button type="button" data-copy="{url}">Copy link</button></div>'''

def art(p):
 return f'''<div class="art" style="--tint:{p['color']}" aria-hidden="true"><div class="art-top"><span>EDRYSTARZ / {p['category'].upper()}</span><span>↗</span></div><strong>{escape(p['name'])}</strong><div class="art-bottom">{p['motif']}</div></div>'''

def card(p,i):
 return f'''<article class="project" data-category="{p['category']}"><a class="art-link" href="/{p['slug']}/" aria-label="Explore {p['name']}">{art(p)}</a><div class="card-meta"><span>{i:02d} / {p['category']}</span><span>{p['status']}</span></div><h3><a href="/{p['slug']}/">{p['name']} <span aria-hidden="true">↗</span></a></h3><p>{escape(p['description'])}</p><a class="text-link" href="/{p['slug']}/">Explore project <span aria-hidden="true">→</span></a></article>'''

(ROOT/'assets').mkdir(exist_ok=True)
index=header('EdryStarz — practical apps & browser extensions','Published browser extensions, local AI learning tools and practical Windows utilities.')+'''<main id="main"><section class="hero"><div class="eyebrow">INDEPENDENT PROJECTS / EDRYSTARZ</div><h1>Small tools.<br><span>Real usefulness.</span></h1><div class="hero-bottom"><p>Browser extensions you can install today.<br>Local AI tools and desktop apps you can explore.<br>Built around everyday problems.</p><a class="button" href="#projects">Find your next useful tool <span>↓</span></a></div><div class="hero-stamp" aria-hidden="true">BUILD<br>USE<br>REPEAT<span>↗</span></div></section><section class="catalog" id="projects"><div class="section-heading"><div><div class="eyebrow">THE PROJECT COLLECTION</div><h2>Pick a problem.<br>Meet a tool.</h2></div><p>Published products first.<br>Prototypes clearly marked.</p></div><div class="filters" role="group" aria-label="Filter projects">'''
index+=''.join(f'<button type="button" data-filter="{x}" aria-pressed="{str(x=="All").lower()}">{x}</button>' for x in ['All','Extensions','Learning','Desktop','Media'])
index+='</div><div class="grid">'+''.join(card(p,i) for i,p in enumerate(PROJECTS,1))+'''</div></section><section class="closing"><div class="eyebrow">FOUND SOMETHING USEFUL?</div><h2>Send it to someone<br>who needs it.</h2><p>Every project has its own link, clear setup and an honest description.</p>'''+share(BASE+'/')+'</section></main>'+footer()
(ROOT/'index.html').write_text(index,encoding='utf-8')
for p in PROJECTS:
 path=p['slug']+'/'; d=ROOT/p['slug'];d.mkdir(exist_ok=True)
 text=header(p['name']+' — EdryStarz',p['description'],path,'assets/'+p['slug']+'.png')+f'''<main id="main"><section class="project-hero"><a class="back" href="/#projects">← All projects</a><div class="eyebrow">{p['category'].upper()} / {p['status'].upper()}</div><h1>{p['name']}</h1><p class="tagline">{p['tag']}</p><p class="lead">{p['description']}</p><div class="actions"><a class="button" href="{p['url']}">{p['action']} ↗</a><a class="button secondary" href="{p['secondary']}">{p['secondary_label']} ↗</a></div></section><section class="detail-grid">{art(p)}<div><div class="eyebrow">WHAT IT DOES</div><h2>A closer look.</h2><p>{p['detail']}</p><ul>'''+''.join('<li>'+escape(f)+'</li>' for f in p['features'])+f'''</ul><p class="stack">{p['stack']}</p><aside>{p['note']}</aside></div></section><section class="closing"><div class="eyebrow">SHARE A USEFUL TOOL</div><h2>{p['tag']}</h2>'''+share(BASE+'/'+path)+f'''<a class="text-link" href="/assets/{p['slug']}.png" download>Download share image ↓</a></section></main>'''+footer()
 (d/'index.html').write_text(text,encoding='utf-8')

# Typographic social cards, not product screenshots.
font_path=Path('C:/Windows/Fonts/arialbd.ttf')
def font(n):return ImageFont.truetype(str(font_path),n) if font_path.exists() else ImageFont.load_default()
for p in [dict(slug='overview',name='Small tools.',tag='Real usefulness.',color='#d5e88c',category='PROJECT COLLECTION')]+PROJECTS:
 im=Image.new('RGB',(1200,630),'#f4f2ea');draw=ImageDraw.Draw(im)
 draw.rectangle((22,22,1178,608),outline='#20231f',width=2)
 draw.rectangle((40,40,1160,90),fill=p['color'])
 draw.text((65,53),'EDRYSTARZ / '+p['category'].upper(),font=font(24),fill='#20231f')
 words=p['name'].split();lines=[];line=''
 for w in words:
  test=(line+' '+w).strip()
  if draw.textlength(test,font=font(84))>1050:lines.append(line);line=w
  else:line=test
 lines.append(line)
 for i,line in enumerate(lines):draw.text((65,170+i*100),line,font=font(84),fill='#20231f')
 draw.text((65,425),p['tag'],font=font(34),fill='#20231f')
 draw.text((65,540),'edrystarz.github.io/'+('' if p['slug']=='overview' else p['slug']+'/'),font=font(26),fill='#33392d')
 im.save(ROOT/'assets'/f"{p['slug']}.png")

(ROOT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#20231f"/><text x="32" y="46" text-anchor="middle" fill="#d5e88c" font-family="Arial" font-weight="bold" font-size="44">e</text></svg>')
(ROOT/'.nojekyll').touch()
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+BASE+'/sitemap.xml\n')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+BASE+'/'+path+'</loc></url>' for path in ['']+[p['slug']+'/' for p in PROJECTS])+'</urlset>')
(ROOT/'projects.json').write_text(json.dumps(PROJECTS,indent=2)+'\n')
print('Generated homepage,',len(PROJECTS),'project pages and share images.')
